import { User } from "../models/User";

export const Users :User[] = [
    {
      uid: "12345",
      userName: "Suggesto_Official",
      userPhotoUrl: "../../../assets/logos/logo.png",
      templateSelected:"one",
      mainProfilLink:"www.instagram.com",
      bioClicks:[
        {
          date:"01/01/2021",
          count:39
        },
        {
          date:"02/01/2021",
          count:24
        },
        {
          date:"03/01/2021",
          count:12
        },
        {
          date:"04/01/2021",
          count:25
        },
        {
          date:"05/01/2021",
          count:32
        },
        {
          date:"06/01/2021",
          count:45
        },
        {
          date:"07/01/2021",
          count:50
        },
        {
          date:"08/01/2021",
          count:54
        },
        {
          date:"09/01/2021",
          count:39
        },
        {
          date:"10/01/2021",
          count:23
        },
        {
          date:"11/01/2021",
          count:45
        },
        {
          date:"12/01/2021",
          count:37
        }
      ],
      bios:[
        {
          name:"instagram",
          photoUrl: "../../../assets/logos/logo.png",
          link:"https://stackoverflow.com/questions/38796541/how-to-add-font-awesome-to-angular-2-cli-project",
          clicks: [
            {
              date:"01/01/2000",
              count:25
            },
            {
              date:"02/01/2000",
              count:29
            },
            {
              date:"03/01/2000",
              count:19
            },
            {
              date:"04/01/2021",
              count:25
            },
            {
              date:"05/01/2021",
              count:32
            },
            {
              date:"06/01/2021",
              count:45
            },
            {
              date:"07/01/2021",
              count:50
            },
            {
              date:"08/01/2021",
              count:54
            },
            {
              date:"09/01/2021",
              count:39
            },
            {
              date:"10/01/2021",
              count:23
            },
            {
              date:"11/01/2021",
              count:45
            },
            {
              date:"12/01/2021",
              count:37
            }
          ]
        },
        {
          name:"facebook",
          photoUrl: "../../../assets/logos/logo.png",
          link:"www.facebook.com",
          clicks: [
            {
              date:"01/01/2000",
              count:79
            },
            {
              date:"02/01/2000",
              count:81
            },
            {
              date:"03/01/2000",
              count:49
            },
            {
              date:"04/01/2021",
              count:25
            },
            {
              date:"05/01/2021",
              count:32
            },
            {
              date:"06/01/2021",
              count:45
            },
            {
              date:"07/01/2021",
              count:50
            },
            {
              date:"08/01/2021",
              count:54
            },
            {
              date:"09/01/2021",
              count:39
            },
            {
              date:"10/01/2021",
              count:23
            },
            {
              date:"11/01/2021",
              count:45
            },
            {
              date:"12/01/2021",
              count:37
            }
          ]
        }
      ]
    },
    {
      uid: "199899",
      userName: "Suggesto_Official",
      userPhotoUrl: "user.png",
      templateSelected:"one",
      mainProfilLink:"www.instagram.com",
      bioClicks:[
        {
          date:"01/01/2021",
          count:39
        },
        {
          date:"02/01/2021",
          count:24
        },
        {
          date:"03/01/2021",
          count:12
        },
        {
          date:"04/01/2021",
          count:25
        },
        {
          date:"05/01/2021",
          count:32
        },
        {
          date:"06/01/2021",
          count:45
        }
      ],
      bios:[
        {
          name:"website",
          photoUrl: "urlphoto",
          link:"www.instagram.com",
          clicks: [
            {
              date:"01/01/2000",
              count:25
            },
            {
              date:"02/01/2000",
              count:29
            },
            {
              date:"03/01/2000",
              count:19
            }
          ]
        },
        {
          name:"facebook",
          photoUrl: "urlphoto",
          link:"www.facebook.com",
          clicks: [
            {
              date:"01/01/2000",
              count:79
            },
            {
              date:"02/01/2000",
              count:81
            },
            {
              date:"03/01/2000",
              count:49
            },
          ]
        }
      ]
    },
    {
      uid: "86464",
      userName: "Suggesto_Official",
      userPhotoUrl: "user.png",
      templateSelected:"one",
      mainProfilLink:"www.instagram.com",
      bioClicks:[
        {
          date:"01/01/2021",
          count:39
        },
        {
          date:"02/01/2021",
          count:24
        },
        {
          date:"03/01/2021",
          count:12
        },
        {
          date:"04/01/2021",
          count:25
        },
        {
          date:"05/01/2021",
          count:32
        },
        {
          date:"06/01/2021",
          count:45
        }
      ],
      bios:[
        {
          name:"website",
          photoUrl: "urlphoto",
          link:"www.instagram.com",
          clicks: [
            {
              date:"01/01/2000",
              count:25
            },
            {
              date:"02/01/2000",
              count:29
            },
            {
              date:"03/01/2000",
              count:19
            }
          ]
        },
        {
          name:"facebook",
          photoUrl: "urlphoto",
          link:"www.facebook.com",
          clicks: [
            {
              date:"01/01/2000",
              count:79
            },
            {
              date:"02/01/2000",
              count:81
            },
            {
              date:"03/01/2000",
              count:49
            },
          ]
        }
      ]
    }
  ];